apiVersion: v1
kind: Namespace
metadata:
  name: microservices


---
apiVersion: v1
kind: Service
metadata:
  name: container1-service
  namespace: microservices
spec:
  selector:
    app: container1
  ports:
    - port: 80
      targetPort: 5000
  type: LoadBalancer